export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const SET_LOGGED_USER = 'SET_LOGGED_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_DASHBOARD_COUNT = 'GET_DASHBOARD_COUNT';

export const GET_SAMPLE_HOUSES = 'GET_SAMPLE_HOUSES';
export const GET_HOUSES = 'GET_HOUSES';
export const GET_HOUSE_DETAILS = 'GET_HOUSE_DETAILS';
export const CREATE_HOUSE = 'CREATE_HOUSE';
export const ADD_UTILITIES = 'ADD_UTILITIES';
export const GET_UTILITIES = 'GET_UTILITIES';
export const ADD_HOUSE_IMAGES = 'ADD_HOUSE_IMAGES';

export const GET_LOCATIONS = 'GET_LOCATIONS';

export const GET_USERS = 'GET_USERS';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';

export const SEARCH_HOUSES = 'SEARCH_HOUSES';
